# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45e630a09f9cd39dc23fbaed924ec6daed6bea8a1375ef7eb45724a2f8800a0013ee325efe62be169e7bca4d0266582532262ccd17cae6f54f74c60a0ceecf36

test:
  secret_key_base: 6653670903bd2d84054b0aa25136affe4f118c27924cb93db309ce80abe01a5ed023c94fb39640ab58a0b70e3466951a7e3ccc0e5a728c962f3e2aa3680e3447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
